export const DEFAULT_VECTOR_DIMENSIONS = 384;
export const DEFAULT_SIMILARITY_THRESHOLD = 0.75;
export const DEFAULT_VECTOR_INDEX_TYPE = "hnsw";
export const DEFAULT_VECTOR_METRIC = "cosine";

export const DEFAULT_FEEDBACK_WEIGHT = 0.1;
export const DEFAULT_IMPORTANCE_DECAY = 0.95;

export const DEFAULT_BACKUP_RETENTION_DAYS = 7;
export const DEFAULT_BACKUP_RETENTION_WEEKS = 4;
export const DEFAULT_BACKUP_RETENTION_MONTHS = 12;
